[files]
extend-exclude = ["changelog", "lapack_lite", "*-notes.rst"]

[default.extend-words]
abd = "abd"
abl = "abl"
acount = "acount"
afe = "afe"
alo = "alo"
alow = "alow"
ands = "ands"
aout = "aout"
arange = "arange"
aranges = "aranges"
arro = "arro"
asign = "asign"
ater = "ater"
ba = "ba"
broadcasti = "broadcasti"
caf = "caf"
cardinalis = "cardinalis"
CLEA = "CLEA"
coalesc = "coalesc"
commenty = "commenty"
commond = "commond"
Comput = "Comput"
cpy = "cpy"
datas = "datas"
dbe = "dbe"
delimitor = "delimitor"
delocate = "delocate"
Destructo = "Destructo"
doub = "doub"
dout = "dout"
evalues = "evalues"
filterd = "filterd"
fo = "fo"
fpr = "fpr"
Empricical = "Empricical"
EXTINT = "EXTINT"
finf = "finf"
Fing = "Fing"
gam = "gam"
gret = "gret"
indx = "indx"
iin = "iin"
iy = "iy"
logist = "logist"
maks = "maks"
mis = "mis"
Mor = "Mor"
nd = "nd"
nin = "nin"
NOO = "NOO"
numer = "numer"
numers = "numers"
Ome = "Ome"
ONO = "ONO"
Onn = "Onn"
ot = "ot"
Packt = "Packt"
padd = "padd"
parms = "parms"
pithon = "pithon"
Pn = "Pn"
seperators = "seperators"
ser = "ser"
siz = "siz"
Strang = "Strang"
srot = "srot"
Tak = "Tak"
thr = "thr"
tpe = "tpe"
ty = "ty"
vor = "vor"
worl = "worl"
zerod = "zerod"
